### ISSUE TITLE
Module not found with cron

### ISSUE THREAD

**Issue by lzpons** [MichaelisTrofficus/hampel_filter#2]
Hi,

I installed hampel on my computer and then on a server. It's called by a single python script using `import hampel`
when I run it manually or on a notebook it works perfect, however when it passes through a crontab I get this execution message 

```
Traceback (most recent call last):
  File "/mellisphera/rundata.py", line 13, in <module>
    import hampel
ImportError: No module named 'hampel'
```

the server works with anaconda distribution
the module seems properly installed in 
`/opt/mellisphera/anaconda3/lib/python3.7/site-packages`

and I've given it wide access rights to avoid any issue on that side

```
drwxrwxrwx  2 lorenzo mellisphera    4096 Jun  7 06:14 hampel-0.0.5.dist-info
-rwxrwxrwx  1 lorenzo mellisphera    2151 Jun  7 06:14 hampel.py
```

Any idea of why the batch mode cannot resolve this module (it resolves all others)?

**Comment by MichaelisTrofficus** [comment]
Hi,

Have you checked which python distribution you are using in the crontab?
Check if the python distro that is executing the job is the same that the
one that has hampel installed.

**Comment by lzpons** [comment]
Thank you for the hint. The crontab is runing on the same user as I was testing on the terminal. But your comment made me think about checking the path and there seems to be the issue.

when runing the script with `crontab` the PATH is extremely basic. 
`/usr/bin:/bin`
as for when I run it on the terminal it is
`/opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin`

That seems to be the reason because in `/usr/bin` there is an old python3.5 distribution that was  being launched

Thanks for your help!

**Comment by MichaelisTrofficus** [comment]
Happy to hear that!!
You are welcome!
