### ISSUE TITLE
Series.fillna with 'method' is deprecated and will raise in a future version.

### ISSUE THREAD

**Issue by jonashoechst** [MichaelisTrofficus/hampel_filter#5]
Recent versions of pandas present a deprecation warning for Series.fillna, which is used in in this module:

```
 /usr/local/lib/python3.11/site-packages/hampel.py:49: FutureWarning:
Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
/usr/local/lib/python3.11/site-packages/hampel.py:50: FutureWarning:
Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
```

Indeed the rolling median computation uses the `fillna()`.

https://github.com/MichaelisTrofficus/hampel_filter/blob/f8970569c847aeac6f24124116bfee9af09d5d3f/src/hampel.py#L49-L50

The warning should be easily fixed by replacing the call by `ffill()` / `bfill()`.

**Comment by MichaelisTrofficus** [comment]
I have changed the implementation of hampel and now it works using Cython, so I guess these warnings shouldn't be present any longer. If you update the version, please take a look at the new README.md (the Usage section) because there are some breaking changes to be considered.
